// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://genyivztjefmjxbopqhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdlbnlpdnp0amVmbWp4Ym9wcWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MzU5MjcsImV4cCI6MjA1NjUxMTkyN30.VggDI7kLWMNAqNDSFmMJDGo1flE6YcwCRuRHtvpQFu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);